In [75]:
def get_sp100():
    import requests 
    import pandas as pd
    from bs4 import BeautifulSoup as bs
    url  = 'https://en.wikipedia.org/wiki/S%26P_100'
    r = requests.get(url)
    soup = bs(r.text, 'lxml')
    table_soup = soup.find("table",{"class":"wikitable sortable"})
    tickers = []

    row_soup = table_soup.find_all('tr')

    for row in row_soup[1:]:      
        td_soup = row.find_all('td')
        tickers.append(td_soup[0].text.replace('\n', '').replace('BRK.B','BRK-B'))
    return tickers

In [76]:
print(get_sp100())

['AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'AIG', 'AMGN', 'AMT', 'AMZN', 'AVGO', 'AXP', 'BA', 'BAC', 'BIIB', 'BK', 'BKNG', 'BLK', 'BMY', 'BRK-B', 'C', 'CAT', 'CHTR', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO', 'CVS', 'CVX', 'DD', 'DHR', 'DIS', 'DOW', 'DUK', 'EMR', 'EXC', 'F', 'FB', 'FDX', 'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM', 'INTC', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LLY', 'LMT', 'LOW', 'MA', 'MCD', 'MDLZ', 'MDT', 'MET', 'MMM', 'MO', 'MRK', 'MS', 'MSFT', 'NEE', 'NFLX', 'NKE', 'NVDA', 'ORCL', 'PEP', 'PFE', 'PG', 'PM', 'PYPL', 'QCOM', 'RTX', 'SBUX', 'SO', 'SPG', 'T', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'V', 'VZ', 'WBA', 'WFC', 'WMT', 'XOM']

In [78]:
def get_yahoo_data(start_date,end_date,tickers):
    from yahoofinancials import YahooFinancials
    import pandas as pd
    dftot = pd.DataFrame(columns=['formatted_date','high','low','adjclose','volume','1daily_return','2daily_return','3daily_return','5daily_return','10daily_return'])
    for i in tickers:
        try:
            yahoo_financials = YahooFinancials(i)
            historical_stock_prices = yahoo_financials.get_historical_price_data(start_date, end_date, 'daily')
            df = pd.DataFrame(historical_stock_prices[i]['prices'])
            df1 = df[['formatted_date','high','low','adjclose','volume']]
            df1['1daily_return'] = (df1.adjclose.shift(-1) - df1.adjclose)/df1.adjclose
            df1['2daily_return'] = (df1.adjclose.shift(-2) -df1.adjclose)/df1.adjclose
            df1['3daily_return'] = (df1.adjclose.shift(-3) - df1.adjclose)/df1.adjclose
            df1['5daily_return'] = (df1.adjclose.shift(-5) - df1.adjclose)/df1.adjclose
            df1['10daily_return'] = (df1.adjclose.shift(-10) - df1.adjclose)/df1.adjclose
            df1['ticker'] = i
            dftot = dftot.append(df1)
        except:
            print(f'{i} has no data for these dates or there is an error')

    return dftot

In [79]:
get_yahoo_data('2020-01-01','2020-01-30',get_sp100())

<ipython-input-78-bfb741be750f>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['1daily_return'] = (df1.adjclose.shift(-1) - df1.adjclose)/df1.adjclose
<ipython-input-78-bfb741be750f>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['2daily_return'] = (df1.adjclose.shift(-2) -df1.adjclose)/df1.adjclose

,formatted_date,high,low,adjclose,volume,1daily_return,2daily_return,3daily_return,5daily_return,10daily_return,ticker
0,2020-01-02,75.150002,73.797501,74.207466,135480400,-0.009722,-0.001831,-0.006526,0.030897,0.049575,AAPL
1,2020-01-03,75.144997,74.125000,73.486023,146322800,0.007968,0.003228,0.019366,0.043372,0.071614,AAPL
2,2020-01-06,74.989998,73.187500,74.071579,118387200,-0.004703,0.011308,0.032788,0.057238,0.055937,AAPL
3,2020-01-07,75.224998,74.370003,73.723213,108872000,0.016086,0.037669,0.040015,0.047890,0.064714,AAPL
4,2020-01-08,76.110001,74.290001,74.909149,132079200,0.021241,0.023550,0.045417,0.026881,0.052904,AAPL
...,...,...,...,...,...,...,...,...,...,...,...
14,2020-01-23,66.930000,66.050003,59.926407,19605900,-0.006739,-0.030403,-0.031751,NaN,NaN,XOM
15,2020-01-24,66.680000,66.040001,59.522533,18238600,-0.023824,-0.025181,-0.033323,NaN,NaN,XOM
16,2020-01-27,65.730003,64.699997,58.104473,21231000,-0.001390,-0.009731,NaN,NaN,NaN,XOM
17,2020-01-28,65.199997,64.629997,58.023705,19664700,-0.008353,NaN,NaN,NaN,NaN,XOM
18,2020-01-29,65.129997,63.900002,57.539047,14202800,NaN,NaN,NaN,NaN,NaN,XOM